
#
# Docs: https://jekyllrb.com/docs/configuration/
title: QUnit
description: The powerful, easy-to-use JavaScript testing framework.
url: "https://api.qunitjs.com"
baseurl: ""
permalink: /:title/
lang: en
timezone: UTC
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: "1,2"
sass:
  # https://jekyllrb.com/docs/assets/#sassscss
  style: compressed
  sourcemap: never
exclude:
  # Don't include these files in the website
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - vendor
  - build

# Theme settings
#
# Amethyst theme options are documented at:
# https://github.com/qunitjs/jekyll-theme-amethyst/blob/main/docs/config.md
#
theme: jekyll-theme-amethyst
amethyst:
  # We keep a classic ICO file as well, for compat with de-facto standard
  # machine discovery, e.g. search engines and analytics software.
  favicon: /favicon.svg
  home_href: https://qunitjs.com
  header_logo:
    src: /img/logo-with-colored-text.svg
    width: 250
    height: 72
  edituri_base: https://github.com/qunitjs/qunit/blob/main/docs/
  release_base: https://github.com/qunitjs/qunit/releases/tag/
  mastodon: https://mastodon.technology/@qunitjs
  twitter: qunitjs
  github: qunitjs
  gitter: qunitjs/qunit
  algolia:
    search_only_api_key: f492bec49e061a41cb8f57128483fd16
    sources:
      - index: qunitjs-api
      - index: qunitjs
        base: https://qunitjs.com


# Backend search settings
#
# This applies to the 'jekyll algolia' command, which is typically
# run from an after a commit is merged. The settings are documented at:
# https://github.com/algolia/jekyll-algolia
#
# To learn how to set this up, refer to:
# https://github.com/qunitjs/jekyll-theme-amethyst/blob/main/docs/getting-started.md#enable-algolia-search
#
algolia:
  application_id: EQYECMT6Q0
  # Which index_name the 'jekyll algolia' command will create or update.
  index_name: qunitjs-api
  # By default only HTML paragraphs are indexed (and headings, albeit through a different mechanism).
  # * Include list items (similar to paragraphs).
  # * Include tables (used for method parameter docs; index per row for better excerpts).
  # * Exclude <pre> (mostly code examples, degrades result quality).
  nodes_to_index: 'p,li,tr'
